/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package main;
import interfaces.BukuPanel;
import interfaces.AuthorPanel;
import kelas.Author;
import kelas.Buku;

// library
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.GridBagLayout;
import java.sql.ResultSet;


/**
 *
 * @author Arik Rizki Akbar
 */

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    dbConnection dbCon = new dbConnection();
    
    // atribut
    // variabel penanda author = true, buku = false
    private boolean isAuthor = false;
    
    // panel author dan buku
    private AuthorPanel authorPanel;
    private BukuPanel bukuPanel;
    
    // fungsi main
    public Main() {
        initComponents();
        
        // koneksi db
        dbCon.connect();
        
        // Awalan hide panel buku dan author
        addAuthorPanel.setVisible(false);
        addBukuPanel.setVisible(false);
        
        // set panel awal
        bukuPanel = new BukuPanel(false);
        bukuPanel.setLayout(new GridBagLayout());
        dataScrollPanel.setViewportView(bukuPanel);
        getDataListBukuDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSwitch = new javax.swing.JToggleButton();
        btnAdd = new javax.swing.JToggleButton();
        addBukuPanel = new javax.swing.JPanel();
        fieldJudul = new javax.swing.JTextField();
        fieldPenerbit = new javax.swing.JTextField();
        fieldAuthor = new javax.swing.JTextField();
        btnBukuSubmit = new javax.swing.JButton();
        labelJudul = new javax.swing.JLabel();
        labelPenerbit = new javax.swing.JLabel();
        labelAuthor = new javax.swing.JLabel();
        labelBukuImage = new javax.swing.JLabel();
        fieldBukuImage = new javax.swing.JTextField();
        labelDeskripsi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldDeskripsi = new javax.swing.JTextArea();
        addAuthorPanel = new javax.swing.JPanel();
        fieldNama = new javax.swing.JTextField();
        fieldJumlahBuku = new javax.swing.JTextField();
        fieldAuthorImage = new javax.swing.JTextField();
        btnAuthorSubmit = new javax.swing.JButton();
        labelNama = new javax.swing.JLabel();
        labelJumlahBuku = new javax.swing.JLabel();
        labelAuthorImage = new javax.swing.JLabel();
        dataScrollPanel = new javax.swing.JScrollPane();
        label_aplikasi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSwitch.setText("Buku");
        btnSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        addBukuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        fieldJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldJudulfieldJudulActionPerformed(evt);
            }
        });

        fieldPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPenerbitfieldPenerbitActionPerformed(evt);
            }
        });

        fieldAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAuthorfieldAuthorActionPerformed(evt);
            }
        });

        btnBukuSubmit.setText("Submit");
        btnBukuSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukuSubmitbtnBukuSubmitActionPerformed(evt);
            }
        });

        labelJudul.setText("Judul");

        labelPenerbit.setText("Penerbit");

        labelAuthor.setText("Author");

        labelBukuImage.setText("Format Image");

        fieldBukuImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBukuImagefieldBukuImageActionPerformed(evt);
            }
        });

        labelDeskripsi.setText("Deskripsi");

        fieldDeskripsi.setColumns(20);
        fieldDeskripsi.setRows(5);
        jScrollPane1.setViewportView(fieldDeskripsi);

        javax.swing.GroupLayout addBukuPanelLayout = new javax.swing.GroupLayout(addBukuPanel);
        addBukuPanel.setLayout(addBukuPanelLayout);
        addBukuPanelLayout.setHorizontalGroup(
            addBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBukuPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(addBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJudul)
                    .addComponent(labelPenerbit)
                    .addComponent(labelAuthor)
                    .addComponent(labelBukuImage)
                    .addComponent(labelDeskripsi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldBukuImage, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addBukuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBukuSubmit)
                .addGap(214, 214, 214))
        );
        addBukuPanelLayout.setVerticalGroup(
            addBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBukuPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(addBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJudul))
                .addGap(12, 12, 12)
                .addGroup(addBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPenerbit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAuthor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldBukuImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBukuImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDeskripsi)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnBukuSubmit)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        addAuthorPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        fieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaActionPerformed(evt);
            }
        });

        fieldJumlahBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldJumlahBukuActionPerformed(evt);
            }
        });

        fieldAuthorImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAuthorImageActionPerformed(evt);
            }
        });

        btnAuthorSubmit.setText("Submit");
        btnAuthorSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorSubmitActionPerformed(evt);
            }
        });

        labelNama.setText("Nama");

        labelJumlahBuku.setText("Jumlah Buku");

        labelAuthorImage.setText("Format Image");

        javax.swing.GroupLayout addAuthorPanelLayout = new javax.swing.GroupLayout(addAuthorPanel);
        addAuthorPanel.setLayout(addAuthorPanelLayout);
        addAuthorPanelLayout.setHorizontalGroup(
            addAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAuthorPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(addAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNama)
                    .addComponent(labelJumlahBuku)
                    .addComponent(labelAuthorImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldAuthorImage, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldJumlahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addAuthorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAuthorSubmit)
                .addGap(161, 161, 161))
        );
        addAuthorPanelLayout.setVerticalGroup(
            addAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAuthorPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(addAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNama))
                .addGap(12, 12, 12)
                .addGroup(addAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldJumlahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJumlahBuku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAuthorImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAuthorImage))
                .addGap(30, 30, 30)
                .addComponent(btnAuthorSubmit)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        dataScrollPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label_aplikasi.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label_aplikasi.setText("Selamat Datang!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dataScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(addAuthorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBukuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(label_aplikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSwitch)
                        .addGap(14, 14, 14)
                        .addComponent(btnAdd))
                    .addComponent(label_aplikasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(addAuthorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBukuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dataScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchActionPerformed
        // TODO add your handling code here:
        
        // jika buku
        if(btnSwitch.isSelected()){
            // add data hide
            addAuthorPanel.setVisible(false);
            addBukuPanel.setVisible(false);
            
            // text button menjadi author
            btnSwitch.setText("Author");
            
            // judul utama menjadi database author
            label_aplikasi.setText("Database Author");
            
            // set true
            isAuthor = true;
            
            // buat panel author
            authorPanel = new AuthorPanel(false);
            
            // dengan grid
            authorPanel.setLayout(new GridBagLayout());
            
            // mengisi panel scrol dengan author panel
            dataScrollPanel.setViewportView(authorPanel);
            
            // dapatkan data
            getDataListAuthorDB();
        }
        
        // jika pilih author
        else {
            
            // hide panel add data
            addAuthorPanel.setVisible(false);
            addBukuPanel.setVisible(false);
            
            // tombol menjadi buku dan
            // judul menjadi database "buku"
            btnSwitch.setText("Buku");
            label_aplikasi.setText("Database Buku");
            
            // author = false
            isAuthor = false;
            
            // tampilkan panel buku
            bukuPanel = new BukuPanel(false);
            
            // dengan grid
            bukuPanel.setLayout(new GridBagLayout());
            
            // mengisi scrol panel kosong dengan panel buku
            dataScrollPanel.setViewportView(bukuPanel);
            
            // dapatkan data list
            getDataListBukuDB();
        }

    }//GEN-LAST:event_btnSwitchActionPerformed

    private void fieldJudulfieldJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldJudulfieldJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldJudulfieldJudulActionPerformed

    private void fieldPenerbitfieldPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPenerbitfieldPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPenerbitfieldPenerbitActionPerformed

    private void fieldAuthorfieldAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAuthorfieldAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAuthorfieldAuthorActionPerformed

    private void btnBukuSubmitbtnBukuSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukuSubmitbtnBukuSubmitActionPerformed
        // TODO add your handling code here:
        
        // get atribut dari field
        String judul = fieldJudul.getText();
        String author = fieldAuthor.getText();
        String penerbit = fieldPenerbit.getText();
        String image_buku = fieldBukuImage.getText();
        String deskripsi = fieldDeskripsi.getText();
        
        // masukkan query insert
        String sql = "insert into `buku` (`judul`, `penerbit`, `author`, `deskripsi`, `image_buku`) "
                + "values (\'"+ judul +"\',\'" + penerbit + "\',\'" + author + "\',\'" + deskripsi + "\',\'" + image_buku + "\')";
        
        // panggil fungsi koneksi query
        dbCon.query(sql);
        
        // hide add data
        addAuthorPanel.setVisible(false);
        addBukuPanel.setVisible(false);
        
        // mengosongkan field
        fieldJudul.setText("");
        fieldPenerbit.setText("");
        fieldAuthor.setText("");
        fieldBukuImage.setText("");
        fieldDeskripsi.setText("");
        
        // tampilkan panel data buku
        // dengan grid
        // mengisi panelscroll
        bukuPanel = new BukuPanel(false);
        bukuPanel.setLayout(new GridBagLayout());
        dataScrollPanel.setViewportView(bukuPanel);
        getDataListBukuDB();
    }//GEN-LAST:event_btnBukuSubmitbtnBukuSubmitActionPerformed

    private void fieldBukuImagefieldBukuImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBukuImagefieldBukuImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBukuImagefieldBukuImageActionPerformed

    private void fieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaActionPerformed

    private void fieldJumlahBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldJumlahBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldJumlahBukuActionPerformed

    private void fieldAuthorImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAuthorImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAuthorImageActionPerformed

    private void btnAuthorSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorSubmitActionPerformed
        // TODO add your handling code here:
        
        // get atribut author dari text field
        String nama = fieldNama.getText();
        int jumlah_buku = Integer.valueOf(fieldJumlahBuku.getText());
        String format_image = fieldAuthorImage.getText();
        
        // query insert
        String sql = "insert into author (nama, jumlah_buku, image_author) "
                + "values (\'" + nama + "\',\'" + jumlah_buku + "\',\'" + format_image + "\')";
        
        // koneksi db
        dbCon.query(sql);
        
        // jide panel add data
        addAuthorPanel.setVisible(false);
        addBukuPanel.setVisible(false);
        
        // empty the input field
        fieldNama.setText("");
        fieldJumlahBuku.setText("");
        fieldAuthorImage.setText("");
        
        // menampilkan kembali data list grid
        authorPanel = new AuthorPanel(false);
        authorPanel.setLayout(new GridBagLayout());
        dataScrollPanel.setViewportView(authorPanel);
        getDataListAuthorDB();
    }//GEN-LAST:event_btnAuthorSubmitActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        // jika add selected
        if(btnAdd.isSelected()){
            // jika author panel = true
            if(isAuthor){
                // tampilkan add data panel author
                addAuthorPanel.setVisible(true);
            }
            // jika author panel = false
            else {
                // tampilkan add data panel buku
                addBukuPanel.setVisible(true);
            }
        }
        // jika tidak selected
        else {
            // hide panel add data
            addAuthorPanel.setVisible(false);
            addBukuPanel.setVisible(false);
        }
    }//GEN-LAST:event_btnAddActionPerformed
    
    // method mendapatkan data author dari database
    // sekaligus menampilkannya
    private void getDataListAuthorDB(){        
        try {
            // query
            String sql = "select * from author";
            ResultSet res = dbCon.getStatement().executeQuery(sql);  
            
            // get atribut
            while (res.next()) {
                Author dataAuthor = new Author(res.getInt("id_author"), res.getString("nama"), res.getInt("jumlah_buku"), res.getString("image_author"));
                
                // tampilkan data
                viewListPanelAuthor(dataAuthor);
            }
        } catch (Exception e) {
            System.err.println("error! " + e.getMessage());
        }
        
    }
    
    // method mendapatkan data Buku dari database
    // sekaligus menampilkannya
    private void getDataListBukuDB(){
        try {
            // Query
            String sql = "select * from buku";
            ResultSet res = dbCon.getStatement().executeQuery(sql);  
            
            // get atribut
            while (res.next()) {
                Buku dataBuku = new Buku(res.getInt("id_buku"), res.getString("judul"), res.getString("penerbit"), res.getString("author"), res.getString("deskripsi"), res.getString("image_buku"));
                
                // tampilkan panel data
                viewListPanelBuku(dataBuku);
            }
        } catch (Exception e) {
            System.err.println("error! " + e.getMessage());
        }
    }
    
    // menampilkan data author dengan list grid
    private void viewListPanelAuthor(Author dataAuthor)
    {
        // grid
        GridBagConstraints gridBC = new GridBagConstraints();
        
        // sbenyak komponen
        gridBC.gridy = authorPanel.getComponentCount();
        gridBC.gridx = 0;
        
        gridBC.fill = GridBagConstraints.HORIZONTAL;
        gridBC.anchor = GridBagConstraints.PAGE_START;
       
        gridBC.insets = new Insets(5, 2, 5, 2);
        AuthorPanel authorPanelTemp = new AuthorPanel(dataAuthor);

        authorPanel.add(authorPanelTemp, gridBC);
        authorPanel.revalidate();
        authorPanel.invalidate();
        authorPanel.repaint();
        pack();
    }   
    
    // menampilkan data buku dengan list grid
    private void viewListPanelBuku(Buku dataBuku)
    {
        // grid
        GridBagConstraints gridBC = new GridBagConstraints();
        
        // sbenyak komponen
        gridBC.gridy = bukuPanel.getComponentCount();
        gridBC.gridx = 0;
        
       
        gridBC.fill = GridBagConstraints.HORIZONTAL;
        gridBC.anchor = GridBagConstraints.PAGE_START;
       
        gridBC.insets = new Insets(5, 2, 5, 2);
        BukuPanel bukuPanelTemp = new BukuPanel(dataBuku);
        
        bukuPanel.add(bukuPanelTemp, gridBC);
        bukuPanel.revalidate();
        bukuPanel.invalidate();
        bukuPanel.repaint();
        pack();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addAuthorPanel;
    private javax.swing.JPanel addBukuPanel;
    private javax.swing.JToggleButton btnAdd;
    private javax.swing.JButton btnAuthorSubmit;
    private javax.swing.JButton btnBukuSubmit;
    private javax.swing.JToggleButton btnSwitch;
    private javax.swing.JScrollPane dataScrollPanel;
    private javax.swing.JTextField fieldAuthor;
    private javax.swing.JTextField fieldAuthorImage;
    private javax.swing.JTextField fieldBukuImage;
    private javax.swing.JTextArea fieldDeskripsi;
    private javax.swing.JTextField fieldJudul;
    private javax.swing.JTextField fieldJumlahBuku;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldPenerbit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAuthor;
    private javax.swing.JLabel labelAuthorImage;
    private javax.swing.JLabel labelBukuImage;
    private javax.swing.JLabel labelDeskripsi;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelJumlahBuku;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelPenerbit;
    private javax.swing.JLabel label_aplikasi;
    // End of variables declaration//GEN-END:variables
}
