/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;
// library
import kelas.Author;
import main.dbConnection;

import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.imageio.ImageIO;
import java.awt.Image;
import java.awt.image.BufferedImage;

/**
 *
 * @author Arik Rizki Akbar
 */

public class AuthorPanel extends javax.swing.JPanel {

    /**
     * Creates new form AuthorPanel
     */
    
    // koneksi database
    dbConnection dbCon = new dbConnection();
    
    // tabel atribut
    Author tAuthor = new Author();
    
    
    // constructor
    public AuthorPanel(boolean empty) {}
    
    public AuthorPanel(Author dataAuthor) {
        initComponents();
        
        // panel update status = hide
        updateAuthorPanel.setVisible(false);
        
        // set label nama dan jumlah buku
        label_nama.setText(dataAuthor.getNama());
        label_jumlahBuku.setText(dataAuthor.getJumlah_buku() + " buku telah terbit.");
        
        // get atribut
        tAuthor.setId_author(dataAuthor.getId_author());
        tAuthor.setNama(dataAuthor.getNama());
        tAuthor.setJumlah_buku(dataAuthor.getJumlah_buku());
        tAuthor.setImage_author(dataAuthor.getImage_author());
        
        // menampilkan image
        BufferedImage image = null;
        
        try {
            image = ImageIO.read(getClass().getResource("/images/" + dataAuthor.getImage_author()));
            Image dImage = image.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            label_image.setIcon(new ImageIcon(dImage));
            
        } catch (Exception e) {
            System.err.println("error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nama = new javax.swing.JLabel();
        label_jumlahBuku = new javax.swing.JLabel();
        label_image = new javax.swing.JLabel();
        updateAuthorPanel = new javax.swing.JPanel();
        fieldNama = new javax.swing.JTextField();
        fieldJumlahBuku = new javax.swing.JTextField();
        fieldAuthorImage = new javax.swing.JTextField();
        btnAuthorUpdate = new javax.swing.JButton();
        labelNama = new javax.swing.JLabel();
        labelJumlahBuku = new javax.swing.JLabel();
        labelAuthorImage = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JToggleButton();
        btnDelete = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label_nama.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        label_nama.setText("Nama");

        label_jumlahBuku.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        label_jumlahBuku.setText("Jumlah Buku");

        label_image.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        fieldNama.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        fieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaActionPerformed(evt);
            }
        });

        fieldJumlahBuku.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        fieldJumlahBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldJumlahBukuActionPerformed(evt);
            }
        });

        fieldAuthorImage.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        fieldAuthorImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAuthorImageActionPerformed(evt);
            }
        });

        btnAuthorUpdate.setText("Update");
        btnAuthorUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorUpdateActionPerformed(evt);
            }
        });

        labelNama.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelNama.setText("Nama");

        labelJumlahBuku.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelJumlahBuku.setText("Jumlah Buku");

        labelAuthorImage.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelAuthorImage.setText("Format Image");

        javax.swing.GroupLayout updateAuthorPanelLayout = new javax.swing.GroupLayout(updateAuthorPanel);
        updateAuthorPanel.setLayout(updateAuthorPanelLayout);
        updateAuthorPanelLayout.setHorizontalGroup(
            updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateAuthorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateAuthorPanelLayout.createSequentialGroup()
                        .addGroup(updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNama)
                            .addComponent(labelJumlahBuku)
                            .addComponent(labelAuthorImage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldAuthorImage, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldJumlahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateAuthorPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAuthorUpdate)
                        .addGap(119, 119, 119)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        updateAuthorPanelLayout.setVerticalGroup(
            updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateAuthorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNama))
                .addGap(12, 12, 12)
                .addGroup(updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldJumlahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJumlahBuku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAuthorImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAuthorImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAuthorUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_image, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_nama)
                                    .addComponent(label_jumlahBuku))
                                .addGap(136, 136, 136))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addGap(46, 46, 46))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(updateAuthorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(label_image, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(label_nama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_jumlahBuku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))
                        .addGap(18, 18, 18)))
                .addComponent(updateAuthorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaActionPerformed

    private void fieldJumlahBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldJumlahBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldJumlahBukuActionPerformed

    private void fieldAuthorImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAuthorImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAuthorImageActionPerformed

    private void btnAuthorUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorUpdateActionPerformed
        // TODO add your handling code here:
        
        // konek database
        dbCon.connect();
        
        // get value dari field
        String nama = fieldNama.getText();
        int jumlah_buku = Integer.valueOf(fieldJumlahBuku.getText());
        String format_image = fieldAuthorImage.getText();
          
        // update database
        String sql = "update `author` set `nama` = \'" + nama + "\',`jumlah_buku` = \'" + jumlah_buku + "\',`image_author` = \'" + format_image + "\' where `id_author` =" + tAuthor.getId_author() + ";";
        dbCon.query(sql);
        
        // mengset kembali data kelas setelah update
        tAuthor.setNama(nama);
        tAuthor.setJumlah_buku(jumlah_buku);
        
        // menampilkan update data
        label_nama.setText(nama);
        label_jumlahBuku.setText(jumlah_buku + " buku telah terbit.");
        
        // menampilkan image
        BufferedImage image = null;
        
        try {
            // get image berdasarkan format nama image
            image = ImageIO.read(getClass().getResource("/images/" + format_image));
            Image dImage = image.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            
            label_image.setIcon(new ImageIcon(dImage));
            
        } catch (Exception e) {
            System.err.println("error: " + e.getMessage());
        }
        
        // hide
        updateAuthorPanel.setVisible(false);
    }//GEN-LAST:event_btnAuthorUpdateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        // jika tombol update true
        if(btnUpdate.isSelected()){
            // tampilkan
            updateAuthorPanel.setVisible(true);
            
            // menampilkan isi field
            fieldNama.setText(tAuthor.getNama());
            fieldJumlahBuku.setText(Integer.toString(tAuthor.getJumlah_buku()));
            fieldAuthorImage.setText(tAuthor.getImage_author());
        }
        else{
            // hide
            updateAuthorPanel.setVisible(false);

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        // opsi button delete
        int optionDelete = 
                JOptionPane.showConfirmDialog(null, "Are you sure?", "Delete", JOptionPane.YES_NO_OPTION);
        
        // jika true
        if(optionDelete == 0){
            // konek ke db
            dbCon.connect();
            
            // query Delete
            String sql = "delete from `author` where `id_author`=" + tAuthor.getId_author();
            dbCon.query(sql);
            
            // hide
            setVisible(false);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuthorUpdate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JToggleButton btnUpdate;
    private javax.swing.JTextField fieldAuthorImage;
    private javax.swing.JTextField fieldJumlahBuku;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JLabel labelAuthorImage;
    private javax.swing.JLabel labelJumlahBuku;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel label_image;
    private javax.swing.JLabel label_jumlahBuku;
    private javax.swing.JLabel label_nama;
    private javax.swing.JPanel updateAuthorPanel;
    // End of variables declaration//GEN-END:variables
}
